name: Java CI with Maven and Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Set up Node.js (for Angular build)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    # Install Angular dependencies
    - name: Install Angular dependencies
      run: |
        cd working/src/main/angular  # Adjust the path if needed
        npm install

    # Build Angular application
    - name: Build Angular app
      run: |
        cd working/src/main/angular  # Adjust the path if needed
        ng build --configuration production

    # Run Angular unit tests with Jest (or other testing frameworks)
    - name: Run Angular unit tests
      run: |
        cd working/src/main/angular  # Adjust the path if needed
        ng test --watch=false --browsers=ChromeHeadless

    # Copy Angular build files to Spring Boot static folder
    - name: Copy Angular build to static folder
      run: |
        cp -r working/src/main/angular/dist/angular/browser/* working/src/main/resources/static/

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build with Maven (Spring Boot)
    - name: Build with Maven
      run: mvn clean install
      working-directory: ./working

    # Run tests with Maven (Spring Boot)
    - name: Run Spring Boot tests
      run: mvn test
      working-directory: ./working

    # Upload build artifact (JAR)
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*.jar

    # Optional: Run Spring Boot Application (uncomment if you want to deploy)
    - name: Run Spring Boot Application
      run: java -jar working/target/working-0.0.1-SNAPSHOT.jar
